hello from Python 3.7.11 in /home/nitai/miniconda3/envs/SimQA-code/bin/python
running train_mle.py experiments
2021-10-14 17:12:15,339 INFO Running on device=`cuda` (device_id=0)
2021-10-14 17:12:19,636 INFO Start training loop and validate every 100 steps...
2021-10-14 17:12:19,638 INFO Loading dataset from data/v3/processed/SimQA.valid.0.pt
2021-10-14 17:12:19,749 INFO number of examples: 534
Traceback (most recent call last):
  File "train_rl.py", line 246, in <module>
    save_checkpoint_steps=opts.save_every,
  File "/home/nitai/SimQA/trainer.py", line 465, in train
    self.validate(valid_iter, src_vocab, moving_average=self.moving_average, stats_cls=stats_cls)
  File "/home/nitai/SimQA/trainer.py", line 619, in validate
    avg_reward /= counter
ZeroDivisionError: division by zero
2021-10-14 17:12:24,123 INFO Running on device=`cuda` (device_id=0)
2021-10-14 17:12:27,987 INFO Start training loop and validate every 100 steps...
2021-10-14 17:12:27,988 INFO Loading dataset from data/v3/processed/SimQA.valid.0.pt
2021-10-14 17:12:28,041 INFO number of examples: 534
Traceback (most recent call last):
  File "train_rl.py", line 246, in <module>
    save_checkpoint_steps=opts.save_every,
  File "/home/nitai/SimQA/trainer.py", line 465, in train
    self.validate(valid_iter, src_vocab, moving_average=self.moving_average, stats_cls=stats_cls)
  File "/home/nitai/SimQA/trainer.py", line 619, in validate
    avg_reward /= counter
ZeroDivisionError: division by zero
